CREATE TABLE cpMovimentos (
	cCPFCNPJCliente,
	cCodCateg VARCHAR(20),
	cGrupo VARCHAR(20),
	cNatureza VARCHAR(1),
	cNumParcela VARCHAR(7),
	cOrigem VARCHAR(4),
	cStatus VARCHAR(50),
	cTipo VARCHAR(5),
	dDtEmissao VARCHAR(10),
	dDtPagamento VARCHAR(10),
	dDtPrevisao VARCHAR(10),
	dDtRegistro VARCHAR(10),
	dDtVenc VARCHAR(10),
	nCodCC BIGINT,
	nCodCliente BIGINT,
	nCodTitRepet BIGINT,
	nCodTitulo BIGINT,
	nValorTitulo NUMERIC,
	cLiquidado VARCHAR(1),
	nDesconto NUMERIC,
	nJuros NUMERIC,
	nMulta NUMERIC,
	nValAberto NUMERIC,
	nValLiquido NUMERIC,
	nValPago NUMERIC
)