CREATE TABLE pedido (
    numero_pedido VARCHAR(15) PRIMARY KEY,
    bloqueado CHAR(1),
    codigo_cenario_impostos VARCHAR(50),
    codigo_cliente BIGINT,
    codigo_pedido BIGINT,
    data_previsao VARCHAR(10),
    etapa INT,
    qtde_parcelas INT,
    quantidade_itens INT,
    valor_frete NUMERIC,
    autorizado CHAR(1),
    cancelado CHAR(1),
    dAlt VARCHAR(10),
    dFat VARCHAR(10),
    dInc VARCHAR(10),
    denegado CHAR(1),
    devolvido CHAR(1),
    devolvido_parcial CHAR(1),
    faturado CHAR(1),
    hAlt VARCHAR(8),
    hFat VARCHAR(8),
    hInc VARCHAR(8),
    codProj BIGINT,
    codVend BIGINT,
    codigo_categoria VARCHAR(50),
    codigo_conta_corrente BIGINT,
    consumidor_final CHAR(1),
    base_calculo_icms NUMERIC,
    valor_descontos NUMERIC,
    valor_mercadorias NUMERIC,
    valor_total_pedido NUMERIC
)